pipeline{
    agent none

    stages{
        stage("Build jar"){
            agent{
                docker{
                    image 'maven:3.9.3-eclipse-temurin-17-focal'
                    args '-u root -v /tmp/m2:/root/.m2'
                }
            }
            steps{
                sh 'mvn clean package -DskipTests'
            }
        }
        stage("Build image"){
            steps{
                script{
                    app = docker.build('mertcany/selenium-grid')
                }
            }
        }
        stage("Push image"){
            steps{
               script{
                    docker.withRegistry('', 'dockerhub-creds')
                        app.push("latest")
               }
            }
        }
    }
}