version: "3"
services:
  hub:
     image: seleniarm/hub:4.10
   #Eğer arayüzde grid istemiyorsak port'u kapatabiliriz
     ports:
       - 4444:4444
  chrome:
    image: seleniarm/node-chromium:4.10
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=TRUE
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox:4.10
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=TRUE
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1

